CREATE DATABASE IF NOT EXISTS bbs DEFAULT CHARACTER SET 'UTF8';
USE bbs;
CREATE TABLE IF NOT EXISTS user(
    uid INT UNSIGNED AUTO_INCREMENT KEY,
    username VARCHAR(20) NOT NULL,
    password VARCHAR(16) NOT NULL
)ENGINE=INNODB CHARSET=UTF8;

INSERT user VALUES (NULL,'Jesse','123');

CREATE TABLE IF NOT EXISTS message(
    mid INT UNSIGNED AUTO_INCREMENT KEY,
    title VARCHAR(50),
    content VARCHAR(1000),
    creatTime VARCHAR(20),
    uid INT UNSIGNED
)ENGINE=INNODB CHARSET=UTF8;

INSERT user VALUES (NULL,'Jesse','123');

ALTER TABLE message
ADD CONSTRAINT uid_fk_userUid FOREIGN KEY(uid) REFERENCES user(uid);

INSERT message VALUES (NULL,'Jesse','123','2018',2);

ALTER TABLE message AUTO_INCREMENT=1;
