/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-04-11 04:33:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dataList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1585292799093L));
    _jspx_dependants.put("jar:file:/E:/epilation/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/epilation/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098682290000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <title>脱毛数据管理系统</title>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/index.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/bootstrap.min.css\">\r\n");
      out.write(" \t\t<script type=\"text/javascript\"  src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery-3.4.1.js\"></script>     \r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("       <header>\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                    <nav>\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/dataList.jsp\" >数据信息</a>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                    <nav>\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/categoryList.jsp\" >数据分类</a>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                   \r\n");
      out.write("            </div>\r\n");
      out.write("        </header>\r\n");
      out.write("        <section class=\"banner\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <h1>脱毛数据管理系统</h1>\r\n");
      out.write("                    <p>数据信息</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <section class=\"main\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\"  style=\"float: right;\">\r\n");
      out.write("                    <div class=\"col-sm-offset-2 col-sm-10\">\r\n");
      out.write("                    \t<!-- 给查询按钮添加id属性，每点击一次按钮进行一次Ajax通信 -->\r\n");
      out.write("                        <button type=\"submit\" id=\"querybtn\" class=\"btn btn-primary\">查询</button>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\" style=\"float: right;width: 300px;\">\r\n");
      out.write("                    <div class=\"col-sm-8\">\r\n");
      out.write("                        <input name=\"searchContent\" class=\"form-control\" id=\"searchContent\"\r\n");
      out.write("                        placeholder=\"输入要查询的数据名称或分类\" style=\"width: 250px\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("                <table class=\"table table-striped\">\r\n");
      out.write("                    <thead>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>序号</th>\r\n");
      out.write("                        <th>数据编号</th>\r\n");
      out.write("                        <th>数据名称</th>\r\n");
      out.write("                        <th>分类</th>\r\n");
      out.write("                        <th>日期</th>\r\n");
      out.write("                        <th>数据图片</th>\r\n");
      out.write("                        <th>操作</th>\r\n");
      out.write("\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                    \r\n");
      out.write("                    \t<!-- 用Ajax实现局部刷新，进行书籍信息展示 -->\r\n");
      out.write("                    \t<script type=\"text/javascript\">\r\n");
      out.write("                    \t\t//给查询按钮绑定点击事件\r\n");
      out.write("                    \t\t$(\"#querybtn\").click(function(){\r\n");
      out.write("                    \t\t\t//将搜索信息作为参数传递给/bookdata,当搜索信息默认为空时，显示所有信息\r\n");
      out.write("                     \t\t\tvar  searchContent = $(\"#searchContent\").val();\r\n");
      out.write("                    \t\t\t$.ajax({\r\n");
      out.write("                    \t\t\t\t\"url\" : \"/epilation/QueryDataServlet\",\r\n");
      out.write("                    \t\t\t\t\"type\" : \"post\",\r\n");
      out.write("                    \t\t\t\t\"data\" :  {\"searchContent\" : searchContent},\r\n");
      out.write("                    \t\t\t\t\"dataType\" : \"json\",\r\n");
      out.write("                    \t\t\t\t\"success\" : function(json){\r\n");
      out.write("                    \t\t\t\t\t//每次要先将tbody内容清空\r\n");
      out.write("                    \t\t\t\t\t$(\"tbody\").empty();\r\n");
      out.write("                    \t\t\t\t\tfor(var i = 0;  i < json.length; i++){\r\n");
      out.write("                    \t\t\t\t\t\tvar ch = json[i];             \r\n");
      out.write("                    \t\t\t\t\t\t$(\"tbody\").append(\"<tr id='tr1'>\"\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t+\"<td>\" + (i+1) + \"</td>\"\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t+\"<td>\"+ch.dataId + \"</td>\"\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t+\"<td>\"+ch.dataName + \"</td>\"\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t+\"<td>\"+ch.categoryName + \"</td>\"\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t+\"<td>\"+ch.dataDate + \"</td>\"\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t+\"<td><img src='/epilation\"+ch.dataPic+ \"' style='width:160px;height:90px'></td>\"\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t+\"<td>\" + \"<a href='/epilation/DataServlet?method=edit&dataId=\" +ch.dataId+ \"'>修改</a> \"\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t+ \" <a href='/epilation/DataServlet?method=delete&dataId=\" +ch.dataId+ \"'>删除</a>\" + \"</td>\"\r\n");
      out.write("                    \t\t\t\t\t\t\t\t\t\t\t\t\t+\"</tr>\");\r\n");
      out.write("                    \t\t\t\t\t}\r\n");
      out.write("                    \t\t\t\t}\r\n");
      out.write("                    \t\t\t})\r\n");
      out.write("                    \t\t})\r\n");
      out.write("                    \t\t//每次进入页面默认触发一次点击事件，进行请求数据\r\n");
      out.write("                    \t\t$('#querybtn').trigger(\"click\")\r\n");
      out.write("                    \t</script>\r\n");
      out.write("                    \t             \t\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <section class=\"page\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div id=\"fatie\">\r\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/addData.jsp\"><button>新建</button></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <footer>\r\n");
      out.write("            ©2020 POWERED BY Jesse\r\n");
      out.write("        </footer>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
